Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
Traceback (most recent call last):
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/loop.py", line 58, in run_forever
    result = self._bot.getUpdates(offset=offset,
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/labra/.local/lib/python3.9/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Gateway', 502, {'ok': False, 'error_code': 502, 'description': 'Bad Gateway'})
